/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept in source control so type-checking
// works in fresh cloud environments before the first local build.
